version: '3'

services:
  djangoapp:
    build: .

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/ssl:/etc/nginx/certs
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp