version: '3'

services:
  djangoapp:
    build: .

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data:/files_to_serve
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp