# Generated by Django 3.0.5 on 2020-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Add a description of your Skills and what you can offer as classes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(default='Add a short description of yourself', max_length=100),
        ),
    ]
