# Generated by Django 3.0.6 on 2020-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200515_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youtube_profile_link',
            field=models.TextField(default=''),
        ),
    ]
