# Generated by Django 3.0.6 on 2020-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_listofinstructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofinstructors',
            name='user_username',
            field=models.TextField(default=''),
        ),
    ]
