# Generated by Django 3.0.6 on 2020-05-20 17:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_listofinstructors_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_logo.PNG', upload_to=users.models.user_directory_path),
        ),
    ]
