# Generated by Django 3.0.6 on 2020-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_signupinstructorlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinstructorlist',
            name='request_info',
            field=models.CharField(default='What are you passionate about teaching?', max_length=150),
        ),
    ]
