# Generated by Django 3.0.6 on 2020-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200617_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinstructorlist',
            name='contact_email',
            field=models.EmailField(default='fake@gmail.com', max_length=254),
        ),
    ]
