# Generated by Django 3.0.6 on 2020-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_signupinstructorlist_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinstructorlist',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
