# Generated by Django 3.0.5 on 2020-04-29 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_cents', models.IntegerField()),
                ('currency', models.CharField(max_length=5)),
                ('user_bought_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Purchases_bought_by', to=settings.AUTH_USER_MODEL)),
                ('user_bought_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Purchases_sold_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
