# Generated by Django 3.0.5 on 2020-04-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200425_1931'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='post_bought_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Item_bought', to='blog.Post'),
        ),
    ]
