# Generated by Django 3.0.5 on 2020-04-29 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_purchases_post_bought_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date_bought',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
