# Generated by Django 3.0.5 on 2020-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_purchases_date_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='cents_string',
            field=models.TextField(default='00'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='dollars_string',
            field=models.TextField(default='0'),
        ),
    ]
