# Generated by Django 3.0.5 on 2020-05-04 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200430_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_by_username', models.TextField()),
                ('bought_from_username', models.TextField()),
                ('stripe_data', models.TextField()),
                ('date_bought', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_bought_from_title', models.TextField()),
            ],
        ),
    ]
