# Generated by Django 3.0.6 on 2020-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_stripeinteractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='user_bought_by_username',
            field=models.TextField(default='someone'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='user_bought_from_username',
            field=models.TextField(default='someone'),
        ),
    ]
