# Generated by Django 3.0.6 on 2020-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200516_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='post_bought_from_title',
            field=models.TextField(default='class title'),
        ),
    ]
