# Generated by Django 3.0.6 on 2020-05-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200520_1249'),
        ('payments', '0007_purchases_post_bought_from_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='post_bought_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Item_bought', to='blog.ClassRoot'),
        ),
    ]
