# Generated by Django 3.0.5 on 2020-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='post',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
