# Generated by Django 3.0.5 on 2020-04-30 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200425_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
