# Generated by Django 3.0.5 on 2020-05-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200430_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_text', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_review', to=settings.AUTH_USER_MODEL)),
                ('quality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.RatingOptions')),
                ('user_being_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
