# Generated by Django 3.0.5 on 2020-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ratingoptions_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='quality',
            new_name='user_rating_out_of_five',
        ),
        migrations.AddField(
            model_name='ratingoptions',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
