# Generated by Django 3.0.5 on 2020-05-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200503_1725'),
        ('blog', '0008_auto_20200502_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Profile'),
        ),
    ]
