# Generated by Django 3.0.6 on 2020-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
