# Generated by Django 3.0.6 on 2020-05-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_faketable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeTable',
        ),
    ]
