# Generated by Django 3.0.6 on 2020-05-17 22:56

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_listofinstructors_user_username'),
        ('blog', '0011_delete_faketable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_purchase', models.BooleanField(default=False)),
                ('is_one_on_one', models.BooleanField(default=False)),
                ('is_stream', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('author_profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Profile')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TimeForClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('00:00', '12:00 AM'), ('00:30', '12:30 AM'), ('01:00', '01:00 AM'), ('01:30', '01:30 AM'), ('02:00', '02:00 AM'), ('02:30', '02:30 AM'), ('03:00', '03:00 AM'), ('03:30', '03:30 AM'), ('04:00', '04:00 AM'), ('04:30', '04:30 AM'), ('05:00', '05:00 AM'), ('05:30', '05:30 AM'), ('06:00', '06:00 AM'), ('06:30', '06:30 AM'), ('07:00', '07:00 AM'), ('07:30', '07:30 AM'), ('08:00', '08:00 AM'), ('08:30', '08:30 AM'), ('09:00', '09:00 AM'), ('09:30', '09:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('13:00', '01:00 PM'), ('13:30', '01:30 PM'), ('14:00', '02:00 PM'), ('14:30', '02:30 PM'), ('15:00', '03:00 PM'), ('15:30', '03:30 PM'), ('16:00', '04:00 PM'), ('16:30', '04:30 PM'), ('17:00', '05:00 PM'), ('17:30', '05:30 PM'), ('18:00', '06:00 PM'), ('18:30', '06:30 PM'), ('19:00', '07:00 PM'), ('19:30', '07:30 PM'), ('20:00', '08:00 PM'), ('20:30', '08:30 PM'), ('21:00', '09:00 PM'), ('21:30', '09:30 PM'), ('22:00', '10:00 PM'), ('22:30', '10:30 PM'), ('23:00', '11:00 PM'), ('23:30', '11:30 PM')], default='17:00', max_length=6)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('classroot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ClassRoot')),
            ],
        ),
        migrations.CreateModel(
            name='ClassVideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ClassRoot')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStreamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_of_viewers', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)])),
                ('classroot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ClassRoot')),
                ('stream_time', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.TimeForClass')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.51)])),
                ('classroot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ClassRoot')),
            ],
        ),
        migrations.CreateModel(
            name='ClassOneOnOneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.TimeForClass')),
                ('classroot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ClassRoot')),
            ],
        ),
    ]
