# Generated by Django 3.0.6 on 2020-05-18 17:38

import blog.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_classoneononeinfo_classpurchaseinfo_classroot_classstreaminfo_classvideoinfo_timeforclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='classvideoinfo',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='classvideoinfo',
            name='video_name',
            field=models.CharField(default='Class Video', max_length=40),
        ),
        migrations.AlterField(
            model_name='classpurchaseinfo',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(3.01)]),
        ),
        migrations.AlterField(
            model_name='timeforclass',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[blog.models.TimeForClass.validate_date], verbose_name='Date'),
        ),
    ]
