# Generated by Django 3.0.6 on 2020-05-18 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200518_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstreaminfo',
            name='max_number_of_viewers',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
