# Generated by Django 3.0.6 on 2020-05-20 16:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200518_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classvideoinfo',
            name='video_file',
            field=models.FileField(null=True, upload_to=blog.models.user_directory_path, verbose_name=''),
        ),
    ]
