# Generated by Django 3.0.6 on 2020-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200520_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoneononeinfo',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
